// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zjf8x6ONg4DLua6kmwrKi7Q08RSRUS8',
    appId: '1:1094165956813:web:20a670ad251bfdc1a08184',
    messagingSenderId: '1094165956813',
    projectId: 'fir-series-67949',
    authDomain: 'fir-series-67949.firebaseapp.com',
    storageBucket: 'fir-series-67949.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1k-8iXDxnMLYfvyiVHJ6_iZHVZK5RaQ',
    appId: '1:1094165956813:android:11729e057d277ff9a08184',
    messagingSenderId: '1094165956813',
    projectId: 'fir-series-67949',
    storageBucket: 'fir-series-67949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUjfGU9KdmZUYySfcKzNJnyQGoXJmlzw',
    appId: '1:1094165956813:ios:609499bd846f9029a08184',
    messagingSenderId: '1094165956813',
    projectId: 'fir-series-67949',
    storageBucket: 'fir-series-67949.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUjfGU9KdmZUYySfcKzNJnyQGoXJmlzw',
    appId: '1:1094165956813:ios:609499bd846f9029a08184',
    messagingSenderId: '1094165956813',
    projectId: 'fir-series-67949',
    storageBucket: 'fir-series-67949.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zjf8x6ONg4DLua6kmwrKi7Q08RSRUS8',
    appId: '1:1094165956813:web:eb5c35611ff356eea08184',
    messagingSenderId: '1094165956813',
    projectId: 'fir-series-67949',
    authDomain: 'fir-series-67949.firebaseapp.com',
    storageBucket: 'fir-series-67949.appspot.com',
  );
}
